# -*- coding: utf-8 -*-
"""Чат_Бот_Colab.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/Shiroshibin/Chat_bot/blob/main/%D0%A7%D0%B0%D1%82_%D0%91%D0%BE%D1%82_Colab.ipynb
"""



url = "https://apply.innopolis.university/?lang=ru&id=12&site=s1&template=university24&landing_mode=edit"
main_page = requests.get(url)
soup_main_page = BeautifulSoup(main_page.text)

card = soup_main_page.find_all("div", class_ = "three-card-slider-description-item__content")

"""Почему имеено Инополис"""

for i in card:
  card_title = i.find("h5", class_ = "three-card-slider-description-item-title").text
  card_text = i.find("p", class_ = "three-card-slider-description-item-text").text
  print(card_title, "\n", card_text, "\n")

undergraduate = soup_main_page.find("div", class_ = "learning-program undergraduate")
program_name = undergraduate.find("h5", class_ = "learning-program-name").text

for i in undergraduate.find("div", class_ = "learning-program-description"):
  text_program = i.find("a")
  if type(i) != None:
    print(text_program.text)



"""## Бакалавриат"""

import requests
from bs4 import BeautifulSoup

url_undergraduate = "https://apply.innopolis.university/bachelor/?lang=ru&id=12&site=s1&template=university24&landing_mode=edit"
main_page_undergraduate = requests.get(url_undergraduate)
soup_main_page_undergraduate = BeautifulSoup(main_page_undergraduate.text)

program_info_card = soup_main_page_undergraduate.find_all("div", class_ = "mainviewport-after-block__main-subtitle")
program_info_card

training_profile = soup_main_page_undergraduate.find_all("div", class_ = "uni-org-main__block")
for i in training_profile:
  training_profile_title = i.find("h3", class_ = "block__title").text
  training_profile_subtitle = i.find("p", class_ = "block__subtitle").text
  print(training_profile_title, "\n",  training_profile_subtitle)

learning_structure = soup_main_page_undergraduate.find("div", class_ = "learning-programs-wrap")

structure_a = learning_structure.find("div", class_ = "learning-program top-right")
structure_a_title = structure_a.find("h5").text
structure_a_text = structure_a.find("div", class_ = "learning-program-description").text

structure_b = learning_structure.find("div", class_ = "learning-program bottom-left")
structure_b_title = structure_b.find("h5", class_ = "learning-program-name").text
structure_b_text = structure_b.find("div", class_ = "learning-program-description").text

structure_c = learning_structure.find("div", class_ = "learning-program bottom-right")
structure_c_title = structure_c.find("h5").text
structure_c_text = structure_c.find("div", class_ = "learning-program-description").text
structure_c_text



reception_company = soup_main_page_undergraduate.find("div", class_ = "container").find_all("div", class_ = "row-info-block__item")
for i in reception_company:
  print(i.text)

admission = soup_main_page_undergraduate.find("div", class_ = "three-cards__wrap container").find_all("div", class_ = "three-cards__main")
for i in admission:
  print(i.text)

"""# Работник 2"""

url = 'https://apply.innopolis.university'

req = requests.get(url)

soup = BS(req.text)

город иннополис



city = soup.find('div', 'campus-info__inno-city')

city_title = city.find('h2')
city_text = city.find('p')

кампус



campus = soup.find('div', 'campus-info-entrants-left')

campus_title_bad = campus.find('h2')

campus_text = campus.find('p')

campus_title = []
for i in campus_title_bad.stripped_strings:
    campus_title.append(i)
   

студенческая жизнь

student = soup.find('div', 'campus-info__student-life')
student_title = student.find('h2')
student_text = student.find('p')

программы подготовки

url = 'https://apply.innopolis.university/master/'
req = requests.get(url)
soup = BS(req.text)

all = soup.find('div', 'uni-org-main__blocks-wrap')

a = []
for i in all:
    print(i.text)


как поступить

all = soup.find('div', 'three-cards__main')

for i in all:
    print(i.text)



all = soup.find('div', 'contacts__requisites')

title = all.find('h2')
working = all.find('div', 'contacts__who')
phone = all.find('div', 'contacts__phone')
mail = all.find('a')
adres = all.find('div', 'contacts__address').find('p')


print(title.text)
print(working.text)
print(phone.text)
print(mail.text)
print(adres.text)

url = "https://apply.innopolis.university/"
req = requests.get(url)
soup = BS(req.text)

bug = soup.find('div', 'learning-programs')
